### ISSUE TITLE
Installation improvement

### ISSUE THREAD

**Issue by crstnio** [roots/docs#128]
[Installing Trellis](https://roots.io/trellis/docs/installing-trellis/)

> Think this can be improved? Please open a thread on our Discourse or contribute on GitHub.

Of course. How about a Roots CLI?

One could just type `roots install`. A bash script could ask what to use (Trellis, Bedrock, Sage) and which project/directory name to use. After that all installation will be done automatically. A CLI could be useful for more installation magic like configuration of Bedrock and Sage, etc.

**Comment by retlehs** [comment]
thanks, we've always wanted this and have worked on it a couple different times in different ways. maybe this year we'll drop something :) 

closing this since we're only tracking docs issues/requests over here. if you wanted to make a feature request on the trellis repo we can keep it open over there
